AWSTemplateFormatVersion: 2010-09-09
Description: Create target bucket to store rg-deployment-docs
Parameters:
  S3NewBucketName:
    Type: String
    Description: "S3 bucket to create."
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9_-]*"
    Default: rg-newdeployment-docs
Resources:
  DeploymentAccessLogsBucketKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key for Deployment Access logs bucket
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM Policies
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"

  DeploymentAccessLogsBucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: S3 bucket hosting access logs shouldn't have access logging configured
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt DeploymentAccessLogsBucketKMSKey.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  DeploymentAccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeploymentAccessLogsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3ServerAccessLogsPolicy-DeploymentBucket
            Action:
              - "s3:PutObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${DeploymentAccessLogsBucket}/deploymentbucket*"
            Principal:
              Service: logging.s3.amazonaws.com
            Condition:
              ArnLike:
                "aws:SourceArn":
                  - !GetAtt DeploymentBucket.Arn
              StringEquals:
                "aws:SourceAccount":
                  - !Sub "${AWS::AccountId}"
  DeploymentBucketKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key for Deployment bucket
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM Policies
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"
  DeploymentBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3NewBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt DeploymentBucketKMSKey.Arn
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      LoggingConfiguration:
        DestinationBucketName: !Ref DeploymentAccessLogsBucket
        LogFilePrefix: deploymentbucket/
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration: # Block all public access configuration for the S3 bucket
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DeploymentBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref DeploymentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceTLS12
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 
              - !Sub '${DeploymentBucket.Arn}'
              - !Sub '${DeploymentBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - Sid: EnforceTLS12OrHigher
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 
              - !Sub '${DeploymentBucket.Arn}'
              - !Sub '${DeploymentBucket.Arn}/*'
            Condition:
              NumericLessThan:
                's3:TLSVersion': '1.2'
Outputs:
  DeploymentBucketCreated:
    Description: Name of the new S3 bucket to store RG Deployment Files
    Value: !Ref DeploymentBucket